### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.recipe.precompiler#2]
Can we have a new release?
And please grant `plone` PyPI rights.

Current PyPI owners or maintainers:
@chaoflow @do3cc @esteele @smcmahon

**Comment by smcmahon** [comment]
I've granted "plone" owner status on pypi. But, given my current disengagement, I'd prefer someone else handle the new release.

**Comment by mauritsvanrees** [comment]
Thanks Steve!
I have released https://pypi.org/project/plone.recipe.precompiler/0.7.2/
